[package]
name = "skall"
version = "0.1.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"

[dependencies]
git2 = { version = "0.10", default-features = false, features = [] }
colored = "1.9"